birdsdir = fileparts(mfilename('fullpath'));

p1 = genpath(fullfile(birdsdir,'sounds'));
addpath( ...
    fullfile(birdsdir,'Baseline') , ...
    fullfile(birdsdir,'FundamentalFreq') , ...
    fullfile(birdsdir,'Helpers') , ...
    fullfile(birdsdir,'csv helpers') , ...
    fullfile(birdsdir,'Harmonic+Noise') , ...
    fullfile(birdsdir,'Generators') , ...
    fullfile(birdsdir,'LongTrill Parameters') , ...
    genpath(fullfile(birdsdir,'Energy')) , ...
    fullfile(birdsdir,'TrillTime') , ...
    fullfile(birdsdir,'Birdsoft') , ...
    fullfile(birdsdir,'Generalization') , ...
    fullfile(birdsdir , 'Longtrill Detection-Alg3') , ...
    fullfile(birdsdir , 'Longtrill Detection - Using AOI') , ...
    p1 , ...
    path);
clear birdsdir p1
